---
name: Add .github/FUNDING.yml
on:
  workflow_call:
    inputs:
      repo:
        type: string
        description: Repository name. e.g. test-1
        required: false
        default: ''
      dry_run:
        description: Run the workflow in dry-run mode
        type: boolean
        required: false
        default: false
    secrets:
      APP_PRIVATE_KEY:
        description: The private key of the GitHub App which has permission to create a pull request
        required: true
      SECUREFIX_CLIENT_PRIVATE_KEY:
        description: The private key of the GitHub App which has permission to create a pull request via SecureFix
        required: true

  workflow_dispatch:
    inputs:
      repo:
        description: Repository name. e.g. test-1
        required: false
        default: ''
      dry_run:
        description: Run the workflow in dry-run mode
        type: boolean
        required: false
        default: false
jobs:
  list:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions: {}
    outputs:
      targets: ${{steps.list.outputs.result}}
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: token
        with:
          app-id: ${{vars.APP_ID}}
          private-key: ${{secrets.APP_PRIVATE_KEY}}
          owner: ${{github.repository_owner}}
          permission-contents: read
          permission-pull-requests: read
          permission-organization-projects: read

      - name: List all repositories
        id: repos
        env:
          GH_TOKEN: ${{steps.token.outputs.token}}
          REPO: ${{inputs.repo}}
        # [
        #   "test-1"
        # ]
        run: |
          if [ -n "${REPO}" ]; then
            {
              echo "value<<EOF"
              echo "[\"${REPO}\"]"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
            exit 0
          fi

          {
            echo "value<<EOF"
            gh repo list "$GITHUB_REPOSITORY_OWNER" \
              -L 10000 \
              --json name \
              --jq '[.[] | .name]'
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: List repositories which already have pull requests
        id: repos_with_prs
        env:
          GH_TOKEN: ${{steps.token.outputs.token}}
          REPO: ${{inputs.repo}}
        # [
        #   "test-1"
        # ]
        run: |
          {
            echo "value<<EOF"
            gh api graphql --paginate --slurp -f query='
            query($endCursor: String) {
              search(first: 100, query:"is:pr project:bulk-pr/1", type:ISSUE, after:$endCursor) {
                pageInfo {
                  hasNextPage
                  endCursor
                }
                nodes {
                  ... on PullRequest {
                    repository {
                      name
                    }
                  }
                }
              }
            }
            ' | jq '[.[] | .data.search.nodes | [.[] | .repository.name]] | add | unique'
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: List repositories which already have FUNDING.yml
        id: fundings
        env:
          GH_TOKEN: ${{steps.token.outputs.token}}
          REPO: ${{inputs.repo}}
        # [
        #   "test-1"
        # ]
        run: |
          {
            echo "value<<EOF"
            gh search code "" \
              --filename FUNDING.yml \
              --owner bulk-pr \
              -L 1000 \
              --json path,repository \
              --jq '[.[] | select(.path == ".github/FUNDING.yml") | .repository.name]'
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - id: list
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          REPOS: ${{steps.repos.outputs.value}}
          FUNDINGS: ${{steps.fundings.outputs.value}}
          REPOS_WITH_PR: ${{steps.repos_with_prs.outputs.value}}
        with:
          script: |
            const repos = JSON.parse(process.env.REPOS);
            const fundings = new Set(JSON.parse(process.env.FUNDINGS));
            const reposWithPR = new Set(JSON.parse(process.env.REPOS_WITH_PR));
            const targets = repos.filter(item => !fundings.has(item) && !reposWithPR.has(item));
            console.log({
              repos: repos,
              fundings: [...fundings],
              reposWithPR: [...reposWithPR],
              targets: targets,
            });
            return targets.slice(0, 256);

  create-pr:
    if: "join(fromJSON(needs.list.outputs.targets), '') != ''"
    runs-on: ubuntu-24.04
    name: create pr (${{matrix.target}})
    timeout-minutes: 10
    permissions: {}
    needs: [list]
    strategy:
      fail-fast: false
      matrix:
        target: ${{fromJSON(needs.list.outputs.targets)}}
    env:
      REPO: ${{matrix.target}}
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: token
        with:
          app-id: ${{vars.APP_ID}}
          private-key: ${{secrets.APP_PRIVATE_KEY}}
          owner: ${{github.repository_owner}}
          repositories: |
            ${{env.REPO}}
          permission-contents: read

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{steps.token.outputs.token}}
          repository: ${{github.repository_owner}}/${{env.REPO}}
          persist-credentials: false

      - run: mkdir -p .github
      - name: Create .github/FUNDING.yml
        env:
          CONTENT: |
            github:
              - suzuki-shunsuke
        run: |
          if [ -f .github/FUNDING.yml ]; then
            echo "::notice:: .github/FUNDING.yml already exists"
            exit 0
          fi
          echo -n "$CONTENT" > .github/FUNDING.yml

      - if: ${{ inputs.dry_run || github.ref_name != 'main' }}
        name: Show diff (Dry run mode)
        uses: bulk-pr/diff-action@d10770b8facffce07143231268942b34418bb67b # v0.0.1

      - if: ${{ !inputs.dry_run && github.ref_name == 'main' }}
        name: Create PR
        uses: csm-actions/securefix-action@038b1b962c37adef7a6612aa91cbfc4d6644feb1 # v0.3.4
        with:
          app_id: ${{vars.SECUREFIX_CLIENT_APP_ID}}
          app_private_key: ${{secrets.SECUREFIX_CLIENT_PRIVATE_KEY}}
          server_repository: securefix-server
          repository: ${{github.repository_owner}}/${{env.REPO}}
          branch: bulk-pr/add-funding-yml
          pull_request_title: "chore: add .github/FUNDING.yml"
          pull_request_body: |
            https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
          pull_request_draft: true
          project_owner: bulk-pr
          project_number: 1
